[tool.black]
line-length = 79
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
line_length = 79
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true
float_to_top = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
exclude = [
  "hil_testing/setup.py",
  "hil_testing/test/test_import_all.py",
]

[[tool.mypy.overrides]]
module = "catkin_pkg.python_setup"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "rospy"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "rosunit"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "std_msgs.*"
ignore_missing_imports = true
