---
    name: pre-commit
    
    on:
      pull_request:
    
    jobs:
      pre-commit:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
          - uses: actions/cache@v3
            name: Cache plugin dir
            with:
              path: ~/.tflint.d/plugins
              key: tflint-${{ hashFiles('.tflint.hcl') }}
          - uses: terraform-linters/setup-tflint@v3
          - uses: pre-commit/action@v3.0.0